# -*- coding: utf-8 -*-
"""hangman

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sy_hJfZq53URqJklh7POCSf0Tu0YIv-8
"""

import random

dictionary = {
    "countries": ["france", "russia", "slovenia", "usa", "bulgaria", "china", "germany", "brazil", "canada", "india", "japan", "australia", "mexico", "italy", "spain"],
    "cities": ["paris", "moscow", "ljubljana", "newyork", "sofia", "beijing", "berlin", "rio", "toronto", "mumbai", "tokyo", "sydney", "mexicocity", "rome", "madrid"]
}

category = ""
while category not in dictionary:
    category = input("Choose a category (countries/cities): ").lower()

word_to_play = random.choice(dictionary[category])
number_of_letters = len(word_to_play)

# Show the first letter and replace other letters with '-'
word_to_show = word_to_play[0] + '-' * (number_of_letters - 1)
print(word_to_show)

allowed_errors = 5
guessed_letters = set()

while True:
    if '-' not in word_to_show:
        print("You won!")
        break

    if allowed_errors == 0:
        print("You lost! The word was:", word_to_play)
        break

    letter = input("Guess a letter: ").lower()

    if len(letter) != 1 or not letter.isalpha():
        print("Please enter a single valid letter.")
        continue

    if letter in guessed_letters:
        print("You already guessed that letter!")
        continue

    guessed_letters.add(letter)

    if letter in word_to_play:
        print(letter + " is in the word!")
        new_word = ""
        for index in range(number_of_letters):
            if word_to_play[index] == letter or word_to_play[index] == word_to_play[0]:
                new_word += word_to_play[index]
            else:
                new_word += word_to_show[index]
        word_to_show = new_word
        print(word_to_show)
    else:
        allowed_errors -= 1
        print("Wrong guess! You are allowed", allowed_errors, "more mistakes.")